#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

"$SCRIPT_DIR/scripts/export-clusterrolebindings.sh"
"$SCRIPT_DIR/scripts/export-clusterrolebinding-self-provisioners.sh"
"$SCRIPT_DIR/scripts/export-cluster-admin-bindings.sh"
"$SCRIPT_DIR/scripts/export-clusterroles.sh"
"$SCRIPT_DIR/scripts/export-clusterversion.sh"
"$SCRIPT_DIR/scripts/export-clusteroperators.sh"
"$SCRIPT_DIR/scripts/export-oauth-cluster.sh"
"$SCRIPT_DIR/scripts/export-oauth-external-auth.sh"
"$SCRIPT_DIR/scripts/export-infrastructure-cluster.sh"
"$SCRIPT_DIR/scripts/export-apiserver-console-access.sh"
"$SCRIPT_DIR/scripts/export-scc-privileged.sh"
"$SCRIPT_DIR/scripts/export-worker-node-auth.sh"
"$SCRIPT_DIR/scripts/export-credential-management.sh"
"$SCRIPT_DIR/scripts/export-platform-guardrails.sh"
"$SCRIPT_DIR/scripts/export-policy-as-code.sh"
"$SCRIPT_DIR/scripts/export-cicd-pipeline-enforcement.sh"
"$SCRIPT_DIR/scripts/export-control-plane-protections.sh"
"$SCRIPT_DIR/scripts/export-patch-lifecycle.sh"
"$SCRIPT_DIR/scripts/export-secrets-cert-rotation.sh"
"$SCRIPT_DIR/scripts/export-disaster-recovery-backup.sh"
"$SCRIPT_DIR/scripts/export-olm-governance.sh"
"$SCRIPT_DIR/scripts/export-etcd-encryption-status.sh"
"$SCRIPT_DIR/scripts/export-governance-policy-ecosystem.sh"
"$SCRIPT_DIR/scripts/export-secrets-integration.sh"
"$SCRIPT_DIR/scripts/export-shared-responsibility-model.sh"
"$SCRIPT_DIR/scripts/export-monitoring-audit-logging.sh"
"$SCRIPT_DIR/scripts/export-configuration-drift-status.sh"
"$SCRIPT_DIR/scripts/export-vulnerability-runtime-detection.sh"

echo "All reports completed."
